### ISSUE TITLE
Implement auto documentation deployment via travis for created package

### ISSUE THREAD

**Issue by lsetiawan** [lsetiawan/rppc#9]
**Do you want to request a feature or report a bug?**
Feature

**What is the current behavior?**
No auto-doc step on `travis.yml` like

```yml
 - if [[ $TEST_TARGET == 'docs' ]]; then
      set -e ;
      conda install --yes doctr ;
      pushd docs ;
      make clean html linkcheck ;
      popd ;
      python -m doctr deploy --sync .;
      python -m doctr deploy --sync --no-require-master --built-docs docs/build/html "docs-$TRAVIS_BRANCH" ;
   fi
```

or automatic generation of keys like

```yml
env:
  global:
    # Doctr deploy key for cormorack/yodapy
    - secure: "hnQJ45kvtEwUZjbbKbjBNDCDnJsp+fCy8ioKw2GV43+S9IpJVV4vqJwsdjPRjdQFB8nVdQTRmfAGPDjqzxO5OACPDBLi7kvl7IpKvZCRW43CVCT9z/bHTCKB5fdqJJgpV0laS9sbvncyjeKMA9l8hvwzyOFLRZ6zYORrBXO3VEieMGRmwTHp9ztbmpJiBTBvzRf3m2xqak9f2/P9JecBELJAfy7Zvcwx8TXOvevmcniJRxPFqgr9iHHAyCU7Agw10j3+rqTOxWEw6iiyD73ZE5sRN3Lf1K2BqehdVAdpdxZpLbdccdTOOm5RpW3OtKhMCGDxOgXhSf1B+kDP/a7ZNAC717QXSp6VXofTkYhE1wvLvj9LTE8sAcWkpItZ8qLYDdmbjPfb5sGhxQhKwUWl8t+DRovTJBi5ogQNOe9V2RMrK79Wpx472GwplsWe+ZHjJ8C6Yyt7F+SruCHmGQr+XmQKgEjDT48gY1Icso7DcpFCvIFrjB2Iw/KsOU2G1BkDdHrseurXGG5V4jriWJFW5XnzrajJYXjAy5cVfuTBoyvzTXM+QM54NhzFNyhnaNKYVhCHb3QZka2BHA8ck79+jMRT7S0pZC31DvqaBEDwEIGORjhxtAYRmfC/KlvuJHmW5yMldMdDC3T6e0O1t3IZvkTF8+gZF3tMr4VZseX2OhE="


```

**What is the expected behavior?**
The secure `env` should be in `.travis.yml` along with the script to make sphinx docs.

**Please mention your Python and operating system version.**
Python 3.6
Ubuntu 17.10
